config/routes.rb
Rails.application.routes.draw do
  
  resources :movies
  resources :series
  resources :documentary_films

  root "home#index"
  get 'documentary_films/index'
  post 'documentary_films/create'
  get 'documentary_films/new'
  get 'series/index' 
  post 'series/create'
  get 'series/new'
  get 'movies/index' 
  post 'movies/create'
  get 'movies/new'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/documentary_film.rb
class DocumentaryFilm < ApplicationRecord
    validates :name, :synopsis, :director, presence: true
end

app/models/movie.rb
class Movie < ApplicationRecord
    validates :name, :synopsis, :director, presence: true
end

app/models/serie.rb
class Serie < ApplicationRecord
    validates :name, :synopsis, :director, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/documentary_films_controller.rb
class DocumentaryFilmsController < ApplicationController
  def index
    @documentary_films = DocumentaryFilm.all
  end

  def create
    @documentary_film = DocumentaryFilm.new(documentary_film_params)
    if @documentary_film.save
      redirect_to documentary_films_path, notice: 'Documental creado exitosamente.'
    else
      render :new
    end
  end

  def new
    @documentary_film = DocumentaryFilm.new
  end

  def documentary_film_params
    params.require(:documentary_film).permit(:name, :synopsis, :director)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
    end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    @movies = Movie.all
  end

  def create
    @movie = Movie.new(movie_params)
    if @movie.save
       redirect_to movies_path, notice: 'Película creada exitosamente.'
    else
       render :new
    end
  end
  
  def new
    @movie = Movie.new
  end

  def movie_params
    params.require(:movie).permit(:name, :synopsis, :director)
  end

end

app/controllers/series_controller.rb
class SeriesController < ApplicationController
  def index
    @series = Serie.all
  end

  def create
    @serie = Serie.new(serie_params)
    if @serie.save
      redirect_to series_index_path, notice: 'Serie creada exitosamente.'
    else
      render :new
    end
  end
  
  def new
    @serie = Serie.new
  end

  def serie_params
    params.require(:serie).permit(:name, :synopsis, :director)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/documentary_films_helper.rb
module DocumentaryFilmsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/series_helper.rb
module SeriesHelper
end

app/views/documentary_films/create.html.erb
<!-- Vista de redirección, no es necesaria -->

app/views/documentary_films/index.html.erb
<div class="container">
    <div class="row">
        <h1>Listado de documentales</h1>
        <% @documentary_films.each do |documentary_film| %>
            <div class="col-md-6">
                <div class="card" style="width: 18rem;">
                    <ul class="list-group list-group-flush">
                      <li class="list-group-item">Nombre: <%= documentary_film.name %></li>
                      <li class="list-group-item">Sinopsis: <%= documentary_film.synopsis %></li>
                      <li class="list-group-item">Director: <%= documentary_film.director %></li>
                    </ul>
                </div>
            </div>
        <% end %>
    </div>
    <div class="row">
        <div class="col-md-12">
            <%= link_to 'Nuevo documental', documentary_films_new_path, class: 'btn btn-primary w-100' %>
        </div>
    </div>
</div>

app/views/documentary_films/new.html.erb
<div class="container">
  <div class="row">
    <h1 class="text-center">Agregar documental</h1>
    <div class="col">
      <%= form_with model: @documentary_film, url: documentary_films_create_path do |form| %>
        <p>
          <%= form.label :name %><br>
          <%= form.text_field :name %>
        </p>
        <p>
          <%= form.label :synopsis %><br>
          <%= form.text_area :synopsis %>
        </p>
        <p>
          <%= form.label :director %><br>
          <%= form.text_field :director %>
        </p>
        <p>
          <%= form.submit 'Guardar' %>
        </p>
      <% end %>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<div class="container py-5">
    <div class="row">
        <div class="col-4">
            <%= link_to 'ver documentales', documentary_films_path, class: "btn btn-primary w-100" %>
        </div>
        <div class="col-4">
            <%= link_to 'ver series', series_index_path, class: "btn btn-primary w-100" %>
        </div>
        <div class="col-4">
            <%= link_to 'ver películas', movies_path, class: "btn btn-primary w-100" %>
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Desafio3</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/movies/create.html.erb
<!-- Vista de redirección, no es necesaria -->

app/views/movies/index.html.erb
<div class="container">
    <div class="row">
        <h1>Listado de películas</h1>
        <% @movies.each do |movie| %>
            <div class="col-md-6">
                <div class="card" style="width: 18rem;">
                    <ul class="list-group list-group-flush">
                      <li class="list-group-item">Nombre: <%= movie.name %></li>
                      <li class="list-group-item">Sinopsis: <%= movie.synopsis %></li>
                      <li class="list-group-item">Director: <%= movie.director %></li>
                    </ul>
                </div>
            </div>
        <% end %>
    </div>
    <div class="row">
        <div class="col-md-12">
            <%= link_to 'Nueva película', movies_new_path, class: 'btn btn-primary w-100' %>
        </div>
    </div>
</div>

app/views/movies/new.html.erb
<div class="container">
  <div class="row">
    <h1 class="text-center">Agregar nueva película</h1>
    <div class="col">
      <%= form_with(model: @movie, url: movies_create_path, local: true) do |form| %>
        <p>
          <%= form.label :name %><br>
          <%= form.text_field :name %>
        </p>
        <p>
          <%= form.label :synopsis %><br>
          <%= form.text_area :synopsis %>
        </p>
        <p>
          <%= form.label :director %><br>
          <%= form.text_field :director %>
        </p>
        <p>
          <%= form.submit 'Guardar' %>
        </p>
      <% end %>
    </div>
  </div>
</div>

app/views/series/create.html.erb
<!-- Vista de redirección, no es necesaria -->

app/views/series/index.html.erb
<div class="container">
    <div class="row">
        <h1>Listado de series</h1>
        <% @series.each do |serie| %>
            <div class="col-md-6">
                <div class="card" style="width: 18rem;">
                    <ul class="list-group list-group-flush">
                      <li class="list-group-item">Nombre: <%= serie.name %></li>
                      <li class="list-group-item">Sinopsis: <%= serie.synopsis %></li>
                      <li class="list-group-item">Director: <%= serie.director %></li>
                    </ul>
                </div>
            </div>
        <% end %>
    </div>
    <div class="row">
        <div class="col-md-12">
            <%= link_to 'Nueva serie', series_new_path, class: 'btn btn-primary w-100' %>
        </div>
    </div>
</div>

app/views/series/new.html.erb
<div class="container">
  <div class="row">
    <h1 class="text-center">Agregar serie</h1>
    <div class="col">
      <%= form_with model: @serie, url: series_create_path do |form| %>
        <p>
          <%= form.label :name %><br>
          <%= form.text_field :name %>
        </p>
        <p>
          <%= form.label :synopsis %><br>
          <%= form.text_area :synopsis %>
        </p>
        <p>
          <%= form.label :director %><br>
          <%= form.text_field :director %>
        </p>
        <p>
          <%= form.submit 'Guardar' %>
        </p>
      <% end %>
    </div>
  </div>
</div>